### ISSUE TITLE
Wonderful! 

### ISSUE THREAD

**Issue by szaghi** [cmacmackin/factual#1]
Great Chris, even more interesting than FIAT!

Why not propose into the Group?

Pay attention: into the README you cite FIAT... cut and paste addiction...

Great Chris!

**Comment by cmacmackin** [comment]
Thanks. I'm just doing it in my own repository because it's just a 
byproduct of my research. I'm getting to the point where I'm writing a 
fluids-solver (for the highly specific case of a couple ice-shelf/plume) 
and when I was thinking through how best to implement it, this struck me 
as a good way. I'm making the fields more general than I strictly need 
(at the moment), but that's all.

On 30/03/16 16:07, Stefano Zaghi wrote:

> Great Chris, even more interesting than FIAT!
> 
> Why not propose into the Group?
> 
> Pay attention: into the README you cite FIAT... cut and paste addiction...
> 
> Great Chris!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/cmacmackin/factual/issues/1

## 

Chris MacMackin
cmacmackin.github.io http://cmacmackin.github.io

**Comment by szaghi** [comment]
There are at least Zaak and me interested in fluid-solver, indeed multi-phase is one of my big interested (yet _unexpressed_). I will study also factual beside FIAT... you give a lot to study!

**Comment by cmacmackin** [comment]
Not so much to study just yet. I've only actually written the abstract 
types so far and their interface is not even 100% stable.

On 30/03/16 16:17, Stefano Zaghi wrote:

> There are at least Zaak and me interested in fluid-solver, indeed 
> multi-phase is one of my big interested (yet /unexpressed/). I will 
> study also factual beside FIAT... you give a lot to study!
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> https://github.com/cmacmackin/factual/issues/1#issuecomment-203484262

## 

Chris MacMackin
cmacmackin.github.io http://cmacmackin.github.io

**Comment by szaghi** [comment]
Yes, I see, but the concept is to study...

Anyway, you are a wiseman to accurately study!

Thank you Chris for sharing your work!
